"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ["app.py"]
DATA_FILES = []
OPTIONS = {
    "iconfile": "assets/icon.icns",
    "plist": {
        "CFBundleName": "Flutter IPA Builder",
        "CFBundleShortVersionString": "0.0.1",
        "CFBundleVersion": "0.0.1",
        "CFBundleIdentifier": "com.ycy.flutteripabuilder",
        "NSHumanReadableCopyright": "Copyright 2024 YCY",
    },
}


setup(
    name="Flutter IPA Builder",
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
